// Re-export from geminiService for convenience
import type {
    ImageGenerationResult as BaseImageGenerationResult,
    VideoOutlineRequest,
    VideoOutlineResponse,
} from '@/services/geminiService';

// Extended version with individual key for re-rendering
export interface ImageGenerationResult extends BaseImageGenerationResult {
    key?: string;
    delay: number; // Delay in milliseconds for loading
}

export type { VideoOutlineRequest, VideoOutlineResponse };

export interface VideoCreationState {
    currentStep: number;
    videoDescription: string;
    searchQuery: string;
    topicSource: string;
    selectedTopic: string;
    targetAudience: string;
    videoGoal: string;
    generatedSummary: string;
    videoStyle: string;
    language: string;
    voiceType: string;
    emotion: string;
    captionStyle: string;
    isGenerating: boolean;
    isPreviewReady: boolean;
    previewUrl: string;
}

export interface ImageGenerationState {
    generatedImages: ImageGenerationResult[];
    isGeneratingImages: boolean;
    hasAutoGeneratedImages: boolean;
    imageGenerationKey: number;
}

export interface ScriptGenerationState {
    videoOutline: VideoOutlineResponse | null;
    isGeneratingOutline: boolean;
}

export interface SearchResult {
    id: number;
    title: string;
    thumbnail: string;
    views: string;
}

export interface TrendingTopic {
    id: string;
    title: string;
    category: string;
    trending: boolean;
}

export interface GeneratedSegment {
    segmentId: number;
    imageUrl: string;
    scriptText: string;
    audioUrl?: string;
    duration?: number;
}
